# Generated by Django 5.2.8 on 2025-11-26 08:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre del autor', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Introduce cuando nacio el autor si lo conoces', null=True)),
                ('death_date', models.DateField(blank=True, help_text='Introduce la fecha de fallecimiento si la conoces', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre  del genero', max_length=200, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre de el idioma', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Introduce el email del estudiante', max_length=100)),
                ('fechini', models.DateField(help_text='Fecha de alta del estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('creditos', models.IntegerField(help_text='Número de créditos enteros')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Introduce el titulo del libro', max_length=200)),
                ('isbn', models.CharField(help_text='Introduce el isbn del libro', max_length=13)),
                ('summary', models.TextField(help_text='Introduce el resumen del libro', max_length=100, verbose_name='descripcion')),
                ('author', models.ForeignKey(blank=True, help_text='Introduce el autor de el libro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librosaut', to='catalog.author')),
                ('genre', models.ManyToManyField(help_text='Introduce el genero del libro', related_name='librosgen', to='catalog.genre')),
                ('original_language', models.ForeignKey(help_text='Introduce el idioma original del libro', on_delete=django.db.models.deletion.RESTRICT, related_name='librosidiom', to='catalog.language')),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(help_text='Introduce los libros del autor', related_name='autores', to='catalog.book'),
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintanance')], default='m', help_text='Introduce el estado del ejemplar')),
                ('imprint', models.CharField(help_text='Introduce los detalles de esta edicion', max_length=100)),
                ('due_back', models.DateField(blank=True, help_text='Introduce la fecha de devolucion del prestamo', null=True)),
                ('book', models.ForeignKey(help_text='Introduce el libro al que pertence el ejemplar', on_delete=django.db.models.deletion.RESTRICT, related_name='instancias', to='catalog.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='EjemploModelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('integer', models.IntegerField()),
                ('float_field', models.FloatField()),
                ('boolean', models.BooleanField(default=False)),
                ('null_boolean', models.BooleanField(null=True)),
                ('big_integer', models.BigIntegerField()),
                ('positive_integer', models.PositiveIntegerField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('file', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('uuid', models.UUIDField(blank=True, default=None, null=True)),
                ('json', models.JSONField(default=dict)),
                ('edad', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\\\+?[0-9]{7,15}$', 'Número no válido')])),
                ('foreign_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='catalog.ejemplomodelos')),
                ('many_to_many', models.ManyToManyField(blank=True, to='catalog.ejemplomodelos')),
                ('one_to_one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='catalog.ejemplomodelos')),
            ],
            options={
                'verbose_name': 'Ejemplo de modelo',
                'verbose_name_plural': 'Ejemplos de modelos',
                'ordering': ['char'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField()),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.coche')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mecanico')),
            ],
        ),
        migrations.AddField(
            model_name='coche',
            name='mecanicos',
            field=models.ManyToManyField(related_name='coches', through='catalog.Reparacion', to='catalog.mecanico'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, help_text='Nota (ej. 9.50)', max_digits=4)),
                ('curso', models.CharField(max_length=100)),
                ('fechini', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de matrícula')),
                ('alumno', models.ForeignKey(help_text='Alumno matriculado', on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
                ('asignatura', models.ForeignKey(help_text='Asignatura matriculada', on_delete=django.db.models.deletion.CASCADE, to='catalog.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('fechini_centro', models.DateField(help_text='Fecha de incorporación al centro')),
                ('centro', models.CharField(max_length=100)),
                ('asignaturas', models.ManyToManyField(help_text='Asociar asignaturas que imparte', to='catalog.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reparacion',
            constraint=models.UniqueConstraint(fields=('mecanico', 'coche', 'fecha_y_hora'), name='unique_reparacion'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('alumno', 'asignatura', 'curso')},
        ),
    ]
