# Generated by Django 6.0 on 2025-12-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprueba', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='mecanicos',
        ),
        migrations.RemoveField(
            model_name='ejemplomodelos',
            name='foreign_key',
        ),
        migrations.RemoveField(
            model_name='ejemplomodelos',
            name='many_to_many',
        ),
        migrations.RemoveField(
            model_name='ejemplomodelos',
            name='one_to_one',
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='asignatura',
        ),
        migrations.RemoveConstraint(
            model_name='reparacion',
            name='unique_reparacion',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='asignaturas',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appprueba.editor'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Introduce cuándo nació el autor si lo conoces', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Introduce el autor del libro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librosaut', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Introduce el género del libro', related_name='librosgen', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Introduce el ISBN del libro', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Introduce el resumen del libro', max_length=100, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Introduce el título del libro', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(help_text='Introduce el libro al que pertenece el ejemplar', on_delete=django.db.models.deletion.RESTRICT, related_name='instancias', to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Introduce la fecha de devolución del préstamo', null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(help_text='Introduce los detalles de esta edición', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance')], default='m', help_text='Introduce el estado del ejemplar', max_length=1),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Introduce el nombre del género', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Introduce el nombre del idioma', max_length=200),
        ),
        migrations.DeleteModel(
            name='EjemploModelos',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='coche',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='mecanico',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Coche',
        ),
        migrations.DeleteModel(
            name='Mecanico',
        ),
        migrations.DeleteModel(
            name='Reparacion',
        ),
    ]
