# Generated by Django 6.0 on 2025-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('pais', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
            ],
        ),
    ]
